version: '3.5'
services:
  app:
    dns: 8.8.8.8
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/src/
      - /src/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:14-alpine
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    ports:
      - 5432:5432
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: pg_boss_db_password
      POSTGRES_DB: pg_boss_dev
    volumes:
      - ./scripts/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql

networks:
  default:
    name: pg_boss_app
