FROM node:18.12.0-alpine
RUN apk add --no-cache g++ make python3 tini
RUN apk add --no-cache libfaketime --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
# Tini is now available at /sbin/tini
ENTRYPOINT ["/sbin/tini", "--"]

ENV WAITFORIT_VERSION="v2.4.1"
ADD https://github.com/maxcnunes/waitforit/releases/download/$WAITFORIT_VERSION/waitforit-linux_amd64 /usr/local/bin/waitforit
RUN chmod +x /usr/local/bin/waitforit

ENV NPM_CONFIG_LOGLEVEL warn
ENV NODE_ENV development
RUN mkdir /src
WORKDIR /src
RUN npm config set cache /home/node/app/.npm-cache --global
COPY package.json package-lock.json /src/
RUN npm i -g @nestjs/cli && npm install

COPY . /src

RUN npm run build

EXPOSE 3000

CMD ["/usr/local/bin/waitforit","-address=tcp://postgres_db:5432", "--", "npm", "run", "start:dev"]
